title: "Deepak Kandasamy | Data Science Leader"
email: "deepak.vk.1994@gmail.com"
description: >-
  Principal Data Scientist specializing in Enterprise AI, Reinforcement Learning, and Generative AI.
baseurl: "/deepak-kandasamy.github.io"
url: "https://deepak-vk-1994.github.io"

# Social Links
github_username: deepak-vk-1994
linkedin_username: deepak-kandasamy

# Jekyll Theme Setup
theme: minima
header_pages:
  - about.md
  - projects.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
